Added shows list
NSS-Day-Cohort-61/Team-1-Magnum pull request #19
Opened 2022-12-01 16:24 UTC by will-hedges

Formatted similarly to Matt's list

2022-12-01 16:26 UTC, loganallengray approved these changes
👍

2022-12-01 16:36 UTC, yerwhile requested changes
show objects do not have genre property (genreId)

2022-12-01 16:37 UTC, will-hedges commented on scripts/shows.js
> +    html += `<li>${show.name} (${show.genre}) starring ${starActor}</li>`;
need to access correct property

2022-12-02 16:09 UTC, will-hedges commented on scripts/shows.js
> +    html += `<li>${show.name} (${show.genre}) starring ${starActor}</li>`;
done

2022-12-02 16:16 UTC, ristopherCh approved these changes

2022-12-02 16:17 UTC, yerwhile approved these changes
I have approved the absolute idea of changes in this module.

2022-12-02 16:17 UTC, merged